### PR TITLE
add recording mime type mp4

### PR DESCRIPTION
**Pull request by zapion**
Add option mp4 for video recording mime type

### CODE REVIEW

**Comment by jds2501** [comment]
This actually doesn't really make sense right now - we don't support h264 with gUM right now.

**Comment by zapion** [comment]
Recorder on firefox os only support mp4, and the mime type of recording will be passed through this option.

**Comment by jds2501** [comment]
Fair enough, you could use this for error testing.

**Comment by zapion** [comment]
I think we can setup another field for mime type of recorder, since it's not necessary to use the same value for both gum and media recorder; they should work fine independently.
Will try to do it.

**Pull request merged**
